name: your_project_name
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: 0.3.0
  flutter_colorpicker: 1.0.3
  usb_serial: 0.4.0
  http: 1.2.2
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Eesti
      fonts:
        - asset: assets/fonts/GT-Eesti-Bold.otf
        - asset: assets/fonts/GT-Eesti-Light.otf
        - asset: assets/fonts/GT-Eesti-Regular.otf
        - asset: assets/fonts/GT-Eesti-Thin.otf
 
  assets:
    - assets/images/blabla_home.png
 